spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.2.101:3306/dreamtale_user
    username: dev
    password: dev001
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.2.101
    port: 6379
  data:
    mongodb:
      host: 192.168.2.101
      port: 27001
      database: dreamtale_user
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dreamtale.user.mapper

